branches:
  only:
  - master
  - develop

sudo: false
language: android
android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # to install Android SDK tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-29.0.2


    # The SDK version used to compile your project
    - android-29

    # Additional components
    # - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support
    # - addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-28
    # - sys-img-x86-android-17

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle

jdk:
  - oraclejdk8


script:
  - ./gradlew build

deploy:
  provider: script
  skip_cleanup: true
  script: ./gradlew bintrayUpload
  on:
    all_branches: true


before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
