name: Android CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  # Job to run Unit and Integration Tests
  unit_integration_tests:

    runs-on: self-hosted
    strategy:
      matrix:
        api-level: [ 34 ]
    env:
      BS_API_USER: ${{ secrets.BS_API_USER }}

      BS_API_PASSWORD: ${{ secrets.BS_API_PASSWORD }}

    if: github.event_name == 'push'
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: 19
          distribution: zulu

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: AVD cache
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}

      - name: Setup Android SDK
        uses: amyu/setup-android@v4

      - name: Gradle build
        run: ./gradlew build --stacktrace

      - name: Run Unit and Integration Tests
        run: ./gradlew :bluesnap-android:testDebugUnitTest


      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2.33.0
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          target: google_apis
          arch: x86_64
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew -i :bluesnap-android:connectedAndroidTest

#  # Job to run Sanity Tests in DemoApp on Pull Requests
#  sanity_tests:
#    runs-on: self-hosted
#    strategy:
#      matrix:
#        api-level: [ 34 ]
#    env:
#      BS_API_USER: ${{ secrets.BS_API_USER }}
#
#      BS_API_PASSWORD: ${{ secrets.BS_API_PASSWORD }}
#
#    if: github.event_name == 'pull_request'
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Set up JDK 19
#        uses: actions/setup-java@v4
#        with:
#          distribution: 'zulu'
#          java-version: '19'
#
#      - name: Gradle cache
#        uses: gradle/actions/setup-gradle@v3
#
#      - name: AVD cache
#        uses: actions/cache@v4
#        id: avd-cache
#        with:
#          path: |
#            ~/.android/avd/*
#            ~/.android/adb*
#          key: avd-${{ matrix.api-level }}
#
#      - name: run SanitySuite UI tests
#        uses: reactivecircus/android-emulator-runner@v2.33.0
#        with:
#          api-level: ${{ matrix.api-level }}
#          force-avd-creation: false
#          target: google_apis
#          arch: x86_64
#          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
#          disable-animations: true
#          script: ./gradlew :DemoApp:connectedDebugAndroidTest --tests "com.bluesnap.android.demoapp.SanitySuite"
#
#
#  # Job to run All UI tests on develop branch
#  ui_tests_on_develop:
#    runs-on: self-hosted
#    strategy:
#      matrix:
#        api-level: [ 34 ]
#    env:
#      BS_API_USER: ${{ secrets.BS_API_USER }}
#
#      BS_API_PASSWORD: ${{ secrets.BS_API_PASSWORD }}
#
#    if: github.ref == 'refs/heads/develop'
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Set up JDK 19
#        uses: actions/setup-java@v3
#        with:
#          distribution: 'zulu'
#          java-version: '19'
#
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Set up JDK 19
#        uses: actions/setup-java@v4
#        with:
#          distribution: 'zulu'
#          java-version: '19'
#
#      - name: Gradle cache
#        uses: gradle/actions/setup-gradle@v3
#
#      - name: AVD cache
#        uses: actions/cache@v4
#        id: avd-cache
#        with:
#          path: |
#            ~/.android/avd/*
#            ~/.android/adb*
#          key: avd-${{ matrix.api-level }}
#
#      - name: run SanitySuite UI tests
#        uses: reactivecircus/android-emulator-runner@v2.33.0
#        with:
#          api-level: ${{ matrix.api-level }}
#          force-avd-creation: false
#          target: google_apis
#          arch: x86_64
#          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
#          disable-animations: true
#          script: ./gradlew :DemoApp:connectedDebugAndroidTest
#
#
