name: Android CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  # Job to run Unit and Integration Tests
  unit_integration_tests:

    runs-on: self-hosted
    strategy:
      matrix:
        api-level: [ 34 ]
    env:
      BS_API_USER: ${{ secrets.BS_API_USER }}
      BS_API_PASSWORD: ${{ secrets.BS_API_PASSWORD }}
      JAVA_OPTS: "-Xmx2g -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false"
      ANDROID_EMULATOR_WAIT_TIME_BEFORE_KILL: 120

#    if: ${{github.event_name == 'push'}}
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: 19
          distribution: zulu

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: Setup Android SDK
        uses: amyu/setup-android@v4
        with:
          # default: false
          # Whether to use the cache
          cache-disabled: true


      - name: Gradle build
        run: ./gradlew build --stacktrace

      - name: Run Unit and Integration Tests
        run: ./gradlew :bluesnap-android:testDebugUnitTest

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2.33.0
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          target: google_apis
          arch: x86_64
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none -netfast
          disable-animations: true
          script: ./gradlew -i :bluesnap-android:connectedAndroidTest

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          include_passed: true
          fail_on_failure: true
          report_paths: '**/build/outputs/androidTest-results/connected/TEST-*.xml'


  #  # Job to run Sanity Tests in DemoApp on Pull Requests
#  sanity_tests:
#    runs-on: self-hosted
#    strategy:
#      matrix:
#        api-level: [ 34 ]
#    env:
#      BS_API_USER: ${{ secrets.BS_API_USER }}
#
#      BS_API_PASSWORD: ${{ secrets.BS_API_PASSWORD }}
#
#    if: github.event_name == 'pull_request'
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Set up JDK 19
#        uses: actions/setup-java@v4
#        with:
#          distribution: 'zulu'
#          java-version: '19'
#
#      - name: Gradle cache
#        uses: gradle/actions/setup-gradle@v3
#
#      - name: AVD cache
#        uses: actions/cache@v4
#        id: avd-cache
#        with:
#          path: |
#            ~/.android/avd/*
#            ~/.android/adb*
#          key: avd-${{ matrix.api-level }}
#
#      - name: run SanitySuite UI tests
#        uses: reactivecircus/android-emulator-runner@v2.33.0
#        with:
#          api-level: ${{ matrix.api-level }}
#          force-avd-creation: false
#          target: google_apis
#          arch: x86_64
#          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
#          disable-animations: true
#          script: ./gradlew :DemoApp:connectedDebugAndroidTest --tests "com.bluesnap.android.demoapp.SanitySuite"
#
#

  # Job to run Unit and Integration Tests
  ui_sanity_tests:

    runs-on: self-hosted
    strategy:
      matrix:
        api-level: [ 34 ]
    env:
      BS_API_USER: ${{ secrets.BS_API_USER }}
      BS_API_PASSWORD: ${{ secrets.BS_API_PASSWORD }}
      JAVA_OPTS: "-Xmx2g -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false"

    #if: github.event_name == 'push'
    #    if: github.event_name == 'pull_request'
    if: ${{github.ref == 'refs/heads/develop-tests'}}
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: 19
          distribution: zulu

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: Setup Android SDK
        uses: amyu/setup-android@v4
        with:
          # default: false
          # Whether to use the cache
          cache-disabled: true


      - name: Gradle build
        run: ./gradlew build --stacktrace

      - name: Run Unit and Integration Tests
        run: ./gradlew :bluesnap-android:testDebugUnitTest

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2.33.0
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          target: google_apis
          arch: x86_64
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none -netfast
          disable-animations: true
          script: ./gradlew :DemoApp:connectedAndroidTest -Pandroid.testInstrumentationRunnerArguments.class=com.bluesnap.android.demoapp.SanitySuite

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/build/outputs/androidTest-results/connected/TEST*.xml'
          include_passed: true
          fail_on_failure: false
